// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARgwDKbk_K8MQOadNCMDnf_Zcnxq5USow',
    appId: '1:64619809857:web:a3bd20a5fcf7bd88cb0ac0',
    messagingSenderId: '64619809857',
    projectId: 'market-place-b0ab5',
    authDomain: 'market-place-b0ab5.firebaseapp.com',
    storageBucket: 'market-place-b0ab5.appspot.com',
    measurementId: 'G-VXWP3DDF0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgyYrrf0Bg_qmqLL3Xq6VJvsuOHSfpNMc',
    appId: '1:64619809857:android:6172c447b01f0242cb0ac0',
    messagingSenderId: '64619809857',
    projectId: 'market-place-b0ab5',
    storageBucket: 'market-place-b0ab5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDQWYXk29SGHbTHFl5zhq8Yb4BXKrQiZw',
    appId: '1:64619809857:ios:56d847bfb9bce78dcb0ac0',
    messagingSenderId: '64619809857',
    projectId: 'market-place-b0ab5',
    storageBucket: 'market-place-b0ab5.appspot.com',
    iosBundleId: 'com.example.adminmarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDQWYXk29SGHbTHFl5zhq8Yb4BXKrQiZw',
    appId: '1:64619809857:ios:7ef710e5a5c7b391cb0ac0',
    messagingSenderId: '64619809857',
    projectId: 'market-place-b0ab5',
    storageBucket: 'market-place-b0ab5.appspot.com',
    iosBundleId: 'com.example.adminmarket.RunnerTests',
  );
}
